<a href="https://colab.research.google.com/github/Munia2319/MachineLearning/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import svm, datasets
iris=datasets.load_iris()

In [ ]:
import pandas as pd
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
df['flower']=iris.target
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [ ]:
df['flower']=df['flower'].apply(lambda x:iris.target_names[x])
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3)

In [ ]:
model=svm.SVC(kernel="rbf",C=30,gamma="auto")
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9333333333333333

In [ ]:
#Now it's time to hyper parameter tuning. let's say we are using SVM and don't know which parameter(C,gamma,kernel or rbf) is best for our problem. so for this we use cross validation or K-fold cross validation
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,20,10],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)
clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00131583, 0.00067286, 0.0007453 , 0.00061212, 0.0007113 ,
        0.00065432]),
 'std_fit_time': array([2.70867473e-04, 7.78094512e-05, 2.82072456e-05, 3.02160537e-05,
        2.33750419e-05, 6.14011120e-05]),
 'mean_score_time': array([0.00063009, 0.00033493, 0.00034685, 0.00031991, 0.00035992,
        0.00034652]),
 'std_score_time': array([1.31675056e-04, 2.96569713e-05, 5.88927673e-06, 1.54051615e-05,
        1.26524587e-05, 6.06154750e-05]),
 'param_C': masked_array(data=[1, 1, 20, 20, 10, 10],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.9       , 0.9       , 0.96666667,
        0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667,
        0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.96666667, 0.96666667, 0.98      ,
        0.97333333]),
 'std_test_score': array([0.01632993, 0.01632993, 0.03651484, 0.0421637 , 0.01632993,
        0.03887301]),
 'rank_test_score': array([1, 1, 5, 6, 1, 4], dtype=int32)}

In [ ]:
df=pd.DataFrame(clf.cv_results_)
df.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001316,0.000271,0.000630,0.000132,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.000673,0.000078,0.000335,0.000030,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000745,0.000028,0.000347,0.000006,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
3,0.000612,0.000030,0.000320,0.000015,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
4,0.000711,0.000023,0.000360,0.000013,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [ ]:
df[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      20          rbf         0.966667
3      20       linear         0.966667
4      10          rbf         0.980000
5      10       linear         0.973333

In [ ]:
#GridSearchcv computes every possible combination but RandomizedSearch Cv  is more efficient which tries only random efficient combination
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,20,10],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False, n_iter=2)
rs.fit(iris.data,iris.target)
rs.cv_results_

{'mean_fit_time': array([0.00146294, 0.00112424]),
 'std_fit_time': array([0.00121497, 0.00014658]),
 'mean_score_time': array([0.0005435, 0.0005003]),
 'std_score_time': array([1.15794345e-04, 3.45440795e-05]),
 'param_kernel': masked_array(data=['linear', 'rbf'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[20, 10],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'linear', 'C': 20}, {'kernel': 'rbf', 'C': 10}],
 'split0_test_score': array([1.        , 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667]),
 'split3_test_score': array([0.93333333, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.96666667, 0.98      ]),
 'std_test_score': array([0.0421637 , 0.01632993]),
 'rank_test_score': array([2, 1], dtype=int32)}

In [ ]:
df=pd.DataFrame(clf.cv_results_)
df[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0      20       linear         0.966667
1      10          rbf         0.980000

In [ ]:
# Now we will choose which is best model to use
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model_params={
    'svm':{
        'model':svm.SVC(gamma='auto'),
        'params':{
            'C':[1,20,10],
            'kernel':['rbf','linear']
        }
    },
     'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
           'n_estimators':[1,5,10]
        }
    },
    'logistic_regression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
           'C':[1,5,10]
        }
    }
}

In [ ]:
scores=[]
for model_name,mp in model_params.items():
 clf=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
 clf.fit(iris.data,iris.target)
 scores.append({
     'model':model_name,
     'best_score':clf.best_score_,
     'best_params':clf.best_params_
 })

In [ ]:
df=pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

                 model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}